postgres:
  host: "localhost"
  port: "5432"
  user: "etl"
  src_db: "pg_sql_ascii_db"
  src_schema: "raw"
  src_tables: ["account"]
  dst_db: "pg_utf8_db"
  dst_schema: "raw"
  dst_tables: ["account"]
  unload_qry: "\\copy (select * from {schema}.{table}) to '{filepath}' with csv header delimiter '{delimiter}' encoding 'SQL_ASCII';"
  load_qry: "\\copy {schema}.{table} from '{filepath}' with csv header delimiter '{delimiter}' encoding 'UTF8';"
  ddl_qry: "select * from public.get_ddl_statement('{schema}', '{table}');"
csv:
  delimiter: ","
  error_handler: "backslashreplace" # Refer to: https://docs.python.org/3/library/codecs.html#error-handlers
app:
  create: True
  load: True