postgres:
  host: "localhost"
  port: "5432"
  user: "etl"
  database: "pg_sql_ascii_db"
  source_tables: ["raw.account"]
  target_tables: ["raw.account"]
  delimiter: ","
  unload_qry: "\\copy (select * from {table}) to '{filepath}' with csv header delimiter '{delimiter}' encoding 'SQL_ASCII';"
  load_qry: "\\copy (select * from {table}) from '{filepath}' with csv header delimiter '{delimiter}' encoding 'UTF8';"
  error_handler: "backslashreplace" # Refer to: Error handler, e.g. ignore, replace, backslashreplace. Refer to: https://docs.python.org/3/library/codecs.html#error-handlers
  load: True