postgres:
  host: "localhost"
  port: "5432"
  user: "etl"
  src_db: "pg_sql_ascii_db"
  src_tables: ["raw.account"]
  dst_db: "pg_utf8_db"
  dst_tables: ["raw.account"]
  unload_qry: "\\copy (select * from {table}) to '{filepath}' with csv header delimiter '{delimiter}' encoding 'SQL_ASCII';"
  load_qry: "\\copy {table} from '{filepath}' with csv header delimiter '{delimiter}' encoding 'UTF8';"
csv:
  delimiter: ","
  error_handler: "backslashreplace" # Refer to: https://docs.python.org/3/library/codecs.html#error-handlers
app:
  load: True