version: 1
formatters:
  simple:
    format: '%(asctime)s %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: info.log
    maxBytes: 4096
    backupCount: 0
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: error.log
    maxBytes: 4096
    backupCount: 0
    encoding: utf8

loggers:
  postgresql-encoding-converter:
    level: INFO
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console, info_file_handler, error_file_handler]